apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8761
  selector:
    app: eureka-server
