version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    networks:
      - fitness-network

  config-server:
    build: ./configserver
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - fitness-network

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - fitness-network

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - config-server
      - eureka
      - userservice
      - activity-service
      - ai-service
    ports:
      - "8080:8080"
    networks:
      - fitness-network

  userservice:
    build: ./userservice
    container_name: user-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - config-server
      - eureka
      - mysql
    ports:
      - "8081:8081"
    networks:
      - fitness-network

  activity-service:
    build: ./activityservice
    container_name: activity-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - config-server
      - eureka
    ports:
      - "8082:8082"
    networks:
      - fitness-network

  ai-service:
    build: ./aiservice
    container_name: ai-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - config-server
      - eureka
    ports:
      - "8083:8083"
    networks:
      - fitness-network

networks:
  fitness-network:
    driver: bridge
