replicaCount: 2

image:
  repository: mokchhedul/userservice
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

database:
  url: jdbc:mysql://mysql-service:3306/fitness_user_db
  username: postgres
  password: admin@123

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
