server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://fitness:5432/fitness_user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

  cloud:
    config:
      uri: http://config-server:8888
