spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
      import: "configserver:http://localhost:8888"  # <-- এটা user-service এর জন্য, config-server এ দরকার নেই

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
