apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app.name }}-pdb
spec:
  minAvailable: {{ sub .Values.replicaCount 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
