apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app.name }}-pdb
spec:
  minAvailable: {{ .Values.replicaCount | int | minus 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
