apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  DB_URL: {{ .Values.database.url }}
  DB_USERNAME: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
