apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
  selector:
    app: config-server
