version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - userservice-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  eureka-server:
    image: eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - userservice-net

  user-service:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DB_URL: jdbc:mysql://mysql:3306/users_db?useSSL=false&serverTimezone=UTC
      DB_USERNAME: user
      DB_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - userservice-net

networks:
  userservice-net:
    driver: bridge
